icon: ğŸ
limits:
  maxWeight: 60
  maxAmount: 140
  maxSpeed: 3
  maxFood: 10
stringTargetMatrix:
  Wolf: 0
  Boa: 0
  Fox: 0
  Bear: 0
  Eagle: 0
  Horse: 0
  Deer: 0
  Rabbit: 0
  Mouse: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 0
  Caterpillar: 0
  Cactus: 100
  Tree: 30
  Bush: 70
  Grass: 100
