icon: ğŸ
limits:
  maxWeight: 15
  maxAmount: 30
  maxSpeed: 1
  maxFood: 3
stringTargetMatrix:
  Wolf: 0
  Fox: 15
  Bear: 0
  Eagle: 0
  Horse: 0
  Deer: 0
  Rabbit: 20
  Mouse: 40
  Goat: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 10
  Caterpillar: 0
  Grass: 0
